function equilbrium = verify(sol_matrix, t_array, time_fraction)
%
% Inputs:
%   SOL_MATRIX - a solution matrix, not the full struct, as contained in
%     structs created by DF
%   T_ARRAY - the time mesh array, as generated by meshgen_t and included
%     in structs created by DF
%   TIME_FRACTION - numeric between 0 and 1. The smaller the stricter the
%     check. When 1: disable the stability check and simply return true.
%     When zero or strictly included between 0 and 1: check if the
%     solution reached a stabilization. Suggested values: 1e-3 for
%     normal cases, 0 for cases in which the stabilization is very
%     important, 1 for cases in which the first solution is needed.
%
% Outputs:
%   equilbrium - a logic asserting if the solution in input reached its
%     equilbrium

%
%------------- BEGIN CODE --------------

equilbrium = true;

if time_fraction >= 1 || time_fraction < 0 || ~isnumeric(time_fraction)
    warning('Driftfusion:verifyJSkip', [mfilename...
        ' - time_fraction is out of [0,1) range: skipping equilbrium check']);
    return
end

% name of the variables
names = ["potential", "electrons", "holes", "cations", "anions"];
% which values have to be considered in a linear or in a log10 scale


% no need to calculate end_time for each of the 4 solutions: if they
% break they break at the same time
% using t(end) could get a time out of the solution when the computation broke before reaching the final time
end_time = t_array(length(sol_matrix(:, 1, 1)));
[~, time_index] = min(abs(t_array - time_fraction * end_time)); % get time mesh index at a specified percentage of maximum time reached


    profile_at_time = sol_matrix(time_index, :, 1); % take profile of values at a certain time of evolution
    profile_end = sol_matrix(end, :, 1); % take profile of values at the end of time


    difference = sum(abs(profile_end - profile_at_time)); % sum up all the differences between the profiles

    threshold = 1e-5 * sum(abs(profile_end - mean(profile_end))); % sum up absolute values, ignore constant bias
    stable = difference <= threshold;

    if stable
        %display(['variable ', num2str(i), ' stabilisation verified']);        
    else
        warning('Driftfusion:verifyJ',...
            'Comparing final solutions at %s s and %s s showed that the %s distribution did not reach stability. Consider trying with a greater tmax.',...
            num2str(t_array(time_index)), num2str(t_array(end)), names(1));
    end
    % true just if all the variables are stabilized
    equilbrium = equilbrium && stable;
end

if equilbrium
    disp("Equilbrium reached");
end

%------------- END OF CODE --------------